### ISSUE TITLE
Custom Recovery Install Query

### ISSUE THREAD

**Issue by ShounenArgha** [Magisk-Modules-Alt-Repo/magic-flash#2]
@HuskyDG 
Can it install custom recovery such as orangefox cause it is flashable zip?
And if there is a mechanizm,please update it to the readme.

Awaiting ur reply,sire!:v:

**Comment by HuskyDG** [comment]
Yes, you can try

**Comment by ShounenArgha** [comment]
> Yes, you can try

Thanks
