### ISSUE TITLE
Flash syntax problem

### ISSUE THREAD

**Issue by ShounenArgha** [Magisk-Modules-Alt-Repo/magic-flash#3]
@HuskyDG 
Sire,
The syntax giving nothing. 

![Screenshot_20220424-190051_Termux](https://user-images.githubusercontent.com/78955676/164977833-cb20a9cf-ca56-4244-9349-2f0fd03091da.jpg)

I typed ```flash "/storage/emulated/0/Download/OrangeFox.zip" ```

I used termux and as su

But it doesn't work

**Comment by HuskyDG** [comment]
Do not use Termux

**Comment by HuskyDG** [comment]
Can you show me what happened after that?

**Comment by ShounenArgha** [comment]
> Can you show me what happened after that?

Like nothing happened.
Lemme give a photo
![Screenshot_20220424-192541_Termux](https://user-images.githubusercontent.com/78955676/164978731-ee44fe95-7235-4fb4-bc87-f1a1b34f676e.jpg)

@HuskyDG

**Comment by ShounenArgha** [comment]
> Do not use Termux

@HuskyDG 
Then what should i use?

**Comment by ShounenArgha** [comment]
Open

**Comment by HuskyDG** [comment]
> Open

What is output of `which unshare` in root shell?

**Comment by HuskyDG** [comment]
Maybe you need to install busybox?

**Comment by ShounenArgha** [comment]
> > Open
> 
> What is output of `which unshare` in root shell?

Nothing
@HuskyDG

**Comment by ShounenArgha** [comment]
Ig i can't do so much hassle.
And thanks for helping

**Comment by HuskyDG** [comment]
Have you tried installing busybox as unshare is missing
