### ISSUE TITLE
[Question] What can this flash?

### ISSUE THREAD

**Issue by TipsyTheCat** [Magisk-Modules-Alt-Repo/magic-flash#4]
The note is a bit unclear.
I'm wondering if this can flash to a different boot partition (_a/_b) safely and what other potential quarks this module possesses.

Thanks in advance! :3

**Comment by TipsyTheCat** [comment]
I'm guessing this module is no longer maintained...

**Comment by HuskyDG** [comment]
Sorry for let you wating...
You can use this command, example for `boot_a` partition:

```
dd if=<boot_image> of=/dev/block/by_name/boot_a
```

**Comment by ProfessorSparrs** [comment]
is this safe to use to flash new Xiaomi Pad 5(nabu)-firmware? This tablet doesnt have a recovery-partition from what Ive read so flashing specific firmware is tricky imho. Or could I flash it via Magisk? Or should it be done in fastboot-mode? I wont flash anything until I know more, either via a reply here or by my Google-Fu :).

**Comment by TipsyTheCat** [comment]
To clarify: This CAN NOT flash firmware?
